### ISSUE TITLE
issue map div is hidden

### ISSUE THREAD

**Issue by monbro** [bevanhunt/meteor-leaflet#59]
I had the issue, that without adding the style:

```css

#map {
  min-height: 350px;
  min-width: 100%;
}
```

my ```<div id='map' class="map"></div>``` would not show up. Maybe its good to add this to the documentation?
